### ISSUE TITLE
Pentaho 6.0/HDP22 Issue

### ISSUE THREAD

**Issue by mrjefflewis** [inquidia/ParquetPlugin#1]
I installed the plugin from the 6.0 Marketplace and followed the instructions. When I open the step dialog I get the following error-

Unable to open dialog for this step
java.lang.NoClassDefFoundError: org/apache/commons/vfs/FileSystemException
    at org.openbi.kettle.plugins.parquetoutput.ParquetOutputDialog.open(ParquetOutputDialog.java:836)
    at org.pentaho.di.ui.spoon.delegates.SpoonStepsDelegate.editStep(SpoonStepsDelegate.java:125)
    at org.pentaho.di.ui.spoon.Spoon.editStep(Spoon.java:8728)
    at org.pentaho.di.ui.spoon.trans.TransGraph.editStep(TransGraph.java:3032)
    at org.pentaho.di.ui.spoon.trans.TransGraph.mouseDoubleClick(TransGraph.java:755)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
    at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
    at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
    at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
    at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
    at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Unknown Source)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
    at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1339)
    at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:7939)
    at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9214)
    at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:653)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.vfs.FileSystemException
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClassFromParent(KettleURLClassLoader.java:89)
    at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClass(KettleURLClassLoader.java:108)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 23 more

**Comment by cdeptula** [comment]
This should be fixed in the v2.0.0 release.
